server:
  port: 8001

eureka:
  instance:
    hostname: 10.7.254.104
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/